# Generated by Django 4.2.30 on 2026-05-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer_name', models.CharField(max_length=255)),
                ('composer_birth_date', models.DateField()),
                ('composer_death_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('youtube_url', models.URLField()),
                ('score_description', models.TextField()),
                ('score_runtime', models.DurationField()),
                ('release_date', models.DateField()),
                ('score_created_at', models.DateTimeField(auto_now_add=True)),
                ('score_updated_at', models.DateTimeField(auto_now=True)),
                ('score_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scores.composer')),
            ],
        ),
    ]
