# Generated by Django 4.2.30 on 2026-05-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='composer',
        ),
        migrations.AddField(
            model_name='score',
            name='composer',
            field=models.ManyToManyField(related_name='scores', to='scores.composer'),
        ),
    ]
