# Generated by Django 4.2.30 on 2026-05-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_remove_score_composer_score_composer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-score_created_at']},
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_runtime',
        ),
        migrations.AlterField(
            model_name='composer',
            name='composer_death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=250)),
                ('track_length', models.DurationField()),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='scores.score')),
            ],
        ),
    ]
